[satusehat]
url = https://api-satusehat-stg.dto.kemkes.go.id
dicom_pathsuffix = /dicom/v1/dicomWeb/studies
fhir_pathsuffix = /fhir-r4/v1
tz_name = Asia/Jakarta
ae_title = DCMROUTER
dicom_port = 11112
dcm_dir = /in/
http_port = 8080
organization_id = 262100fb-b21b-49f9-b6ea-643214681f79
client_key = Zf43GJg7nX5hNcK0m12hulmgisAQoQQymdz1LSxBooYiBKbC
secret_key = VrrPp92nKaBy406USKZE6vHBM9tRaUQduDB4AzuQIFXciVIWajXyKrFSpQuGmRC3
calling_ae_title = DCM4CHEE
