[satusehat]
url = https://api-satusehat-stg.dto.kemkes.go.id
dicom_pathsuffix = /dicom/v1/dicomWeb/studies
fhir_pathsuffix = /fhir-r4/v1
tz_name = Asia/Jakarta
ae_title = DCMROUTER
dicom_port = 11112
dcm_dir = /in/
http_port = 8080
organization_id = 100025504
client_key = BCImTBSSvcc7R7pqERwqd5V3ZAEMcmnuhMAlsSfrpljcGIyI
secret_key = NT57LNr6KCHz5RqKYtxQVmV9BgA7XDRRIqpt39ysefo1HjAXY4KAbYIrDdegnauB
calling_ae_title = DCM4CHEE
